
EMAIL_RATING_OK = 0
EMAIL_RATING_BORDERLINE = 10
EMAIL_RATING_USELESS = 30

EMAIL_RATINGS = (
	(EMAIL_RATING_OK, 'OK'),
	(EMAIL_RATING_BORDERLINE, 'Borderline'),
	(EMAIL_RATING_USELESS, 'Useless'),
)
EMAIL_RATINGS_DICT = dict(EMAIL_RATINGS)